export const courses = [
        {
            title: 'Tutorial: How to use Procreate',
            rating: 2,
            h2: 'Basic learning of how  to use procreate',
            h3: 'Course Content',
            body: 'How to use brush, how to use app, how to adjust brush, canvas size',
            author: 'Anna',
            image: require('../assets/procreate.png'),
            key: '1',
            moments: [
                 {
                 id: '1',
                 title: 'Creator and Class introduction',
                 h1: 'This video shows:',
                 details: 'Details number one, details number',
                 videoUrl: 'https://www.youtube.com/watch?v=AWmWWTBBxv4'
                  },
                                     {
                                     id: '2',
                                     title: 'Introduction to work environment',
                                     details: 'Details number one, details number',
                                     videoUrl: ''},
                                     { id: '3', title: 'Installing Procreate', details: 'Details number one, details number' },
                                     { id: '4', title: 'All procreate function', details: 'Details number one, details number' },
                                     { id: '5', title: 'Canvas', details: 'Details number one, details number'},
                                     { id: '6', title: 'Brush', details: 'Details number one, details number' },
                                     { id: '7', title: 'Animation' , details: 'Details number one, details number'},
                                     { id: '8', title: '3D Model', details: 'Details number one, details number' },
            ]
        },
        {
          title: 'Digital art: Environment drawing',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          image: require('../assets/logo.png'),
          key: '2',
          moments: [
                     { id: '1', title: 'Creator and Class introduction', details: 'Details number one, details number' },
                                         { id: '2', title: 'Introduction to work environment', details: 'Details number one, details number' },
                                         { id: '3', title: 'Installing Procreate', details: 'Details number one, details number' },
                                         { id: '4', title: 'All procreate function', details: 'Details number one, details number' },
                                         { id: '5', title: 'Canvas', details: 'Details number one, details number'},
                                         { id: '6', title: 'Brush', details: 'Details number one, details number' },
                                         { id: '7', title: 'Animation' , details: 'Details number one, details number'},
                                         { id: '8', title: '3D Model', details: 'Details number one, details number' },
                               ]
               },
        {
          title: 'Step by step: Character design.',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          image: require('../assets/draw.png'),
          key: '3',
          moments: [
                     { id: '1', title: 'Creator and Class introduction', details: 'Details number one, details number' },
                                         { id: '2', title: 'Introduction to work environment', details: 'Details number one, details number' },
                                         { id: '3', title: 'Installing Procreate', details: 'Details number one, details number' },
                                         { id: '4', title: 'All procreate function', details: 'Details number one, details number' },
                                         { id: '5', title: 'Canvas', details: 'Details number one, details number'},
                                         { id: '6', title: 'Brush', details: 'Details number one, details number' },
                                         { id: '7', title: 'Animation' , details: 'Details number one, details number'},
                                         { id: '8', title: '3D Model', details: 'Details number one, details number' },
                               ]
               },
        {
          title: 'Tutorial: How to use Procreate',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          image: require('../assets/baby.png'),
          key: '4',
          moments: [
                    { id: '1', title: 'Creator and Class introduction', details: 'Details number one, details number' },
                                        { id: '2', title: 'Introduction to work environment', details: 'Details number one, details number' },
                                        { id: '3', title: 'Installing Procreate', details: 'Details number one, details number' },
                                        { id: '4', title: 'All procreate function', details: 'Details number one, details number' },
                                        { id: '5', title: 'Canvas', details: 'Details number one, details number'},
                                        { id: '6', title: 'Brush', details: 'Details number one, details number' },
                                        { id: '7', title: 'Animation' , details: 'Details number one, details number'},
                                        { id: '8', title: '3D Model', details: 'Details number one, details number' },
                           ]
                       },
        {
          title: 'Tutorial: How to use Procreate',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          key: '5',
          moments: [
                     { id: '1', title: 'Creator and Class introduction', details: 'Details number one, details number' },
                     { id: '2', title: 'Introduction to work environment', details: 'Details number one, details number' },
                     { id: '3', title: 'Installing Procreate', details: 'Details number one, details number' },
                     { id: '4', title: 'All procreate function', details: 'Details number one, details number' },
                     { id: '5', title: 'Canvas', details: 'Details number one, details number'},
                     { id: '6', title: 'Brush', details: 'Details number one, details number' },
                     { id: '7', title: 'Animation' , details: 'Details number one, details number'},
                     { id: '8', title: '3D Model', details: 'Details number one, details number' },
                                   ]
                               },
    ];
