export const courses = [
        {
            title: 'Tutorial: How to use Procreate',
            rating: 2,
            h2: 'Basic learning of how  to use procreate',
            h3: 'Course Content',
            body: 'How to use brush, how to use app, how to adjust brush, canvas size',
            author: 'Anna',
            key: '1',
            moments: [
                { id: '1', title: 'Creator and Class introduction' },
                { id: '2', title: 'Introduction to work environment' },
                { id: '3', title: 'Installing Procreate' },
                { id: '4', title: 'All procreate function' },
                { id: '5', title: 'Canvas' },
                { id: '6', title: 'Brush' },
                { id: '7', title: 'Animation' },
                { id: '8', title: '3D Model' },
            ]
        },
        {
          title: 'Digital art: Environment drawing',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          key: '2',
          moments: [
                    { id: '1', title: 'Creator and Class introduction' },
                    { id: '2', title: 'Introduction to work environment' },
                    { id: '3', title: 'Installing Procreate' },
                    { id: '4', title: 'All procreate function' },
                    { id: '5', title: 'Choosing brush and Canvas' },
                    { id: '6', title: 'Brush' },
                    { id: '7', title: 'Animation' },
                    { id: '8', title: '3D Model' },
                               ]
               },
        {
          title: 'Step by step: Character design.',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          key: '3',
          moments: [
                     { id: '1', title: 'Creator and Class introduction' },
                     { id: '2', title: 'Introduction to work environment' },
                     { id: '3', title: 'Installing Procreate' },
                     { id: '4', title: 'All procreate function' },
                     { id: '5', title: 'Canvas' },
                     { id: '6', title: 'Brush' },
                     { id: '7', title: 'Animation' },
                     { id: '8', title: '3D Model' },
                               ]
               },
        {
          title: 'Tutorial: How to use Procreate',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          key: '4',
          moments: [
                     { id: '1', title: 'Creator and Class introduction' },
                     { id: '2', title: 'Introduction to work environment' },
                     { id: '3', title: 'Installing Procreate' },
                     { id: '4', title: 'All procreate function' },
                     { id: '5', title: 'Canvas' },
                     { id: '6', title: 'Brush' },
                     { id: '7', title: 'Animation' },
                     { id: '8', title: '3D Model' },
                           ]
                       },
        {
          title: 'Tutorial: How to use Procreate',
          rating: 2,
          h2: 'Basic learning of how  to use procreate',
          h3: 'Course Content',
          body: 'How to use brush, how to use app, how to adjust brush, canvas size',
          author: 'Anna',
          key: '5',
          moments: [
                     { id: '1', title: 'Creator and Class introduction' },
                     { id: '2', title: 'Introduction to work environment' },
                     { id: '3', title: 'Installing Procreate' },
                     { id: '4', title: 'All procreate function' },
                     { id: '5', title: 'Canvas' },
                     { id: '6', title: 'Brush' },
                     { id: '7', title: 'Animation' },
                     { id: '8', title: '3D Model' },
                                   ]
                               },
    ];
